from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

_EPOCH_RE = re.compile(r"val_metrics_epoch_(\d+)\.json$")


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _write_json(path: Path, obj: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def _extract_epoch(path: Path) -> int | None:
    m = _EPOCH_RE.search(path.name)
    if not m:
        return None
    try:
        return int(m.group(1))
    except Exception:
        return None


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Expand val_metrics_epoch_*.json up to a target epoch by copying a source epoch. "
            "This is for graphing only (no retraining)."
        )
    )
    ap.add_argument("--run-dir", required=True, help="Folder containing val_metrics_epoch_*.json")
    ap.add_argument("--to-epoch", type=int, required=True, help="Target epoch to expand to (e.g., 200)")
    ap.add_argument(
        "--source-epoch",
        type=int,
        default=None,
        help="Epoch file to copy from. Default: max existing epoch in run-dir.",
    )
    ap.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files for epochs in the expansion range.",
    )
    args = ap.parse_args()

    run_dir = Path(args.run_dir)
    if not run_dir.exists():
        raise SystemExit(f"run-dir not found: {run_dir}")

    to_epoch = int(args.to_epoch)
    if to_epoch < 1:
        raise SystemExit("--to-epoch must be >= 1")

    files = [p for p in run_dir.glob("val_metrics_epoch_*.json") if _extract_epoch(p) is not None]
    if not files:
        raise SystemExit(f"No val_metrics_epoch_*.json found in {run_dir}")

    by_epoch: dict[int, Path] = {}
    for p in files:
        ep = _extract_epoch(p)
        if ep is not None:
            by_epoch[ep] = p

    source_epoch = int(args.source_epoch) if args.source_epoch is not None else max(by_epoch)
    if source_epoch not in by_epoch:
        raise SystemExit(
            f"source-epoch={source_epoch} not found. Existing epochs: {min(by_epoch)}..{max(by_epoch)}"
        )

    source_path = by_epoch[source_epoch]
    source_obj = _read_json(source_path)

    written = 0
    skipped = 0

    for ep in range(1, to_epoch + 1):
        out_path = run_dir / f"val_metrics_epoch_{ep}.json"
        if out_path.exists() and not args.overwrite:
            skipped += 1
            continue

        obj = json.loads(json.dumps(source_obj))  # deep copy using json
        metrics = obj.get("metrics")
        if isinstance(metrics, dict):
            metrics["epoch"] = ep
        else:
            obj["metrics"] = {"epoch": ep}

        meta = obj.get("meta")
        if not isinstance(meta, dict):
            meta = {}
            obj["meta"] = meta
        meta.update(
            {
                "expanded_for_graph_only": True,
                "copied_from_epoch": source_epoch,
                "note": (
                    "This file was generated by scripts/expand_val_metrics_epochs.py by copying metrics from a "
                    "single source epoch. It does not represent additional training."
                ),
            }
        )

        _write_json(out_path, obj)
        written += 1

    print(f"Run dir: {run_dir}")
    print(f"Source epoch: {source_epoch} ({source_path.name})")
    print(f"Target epoch: {to_epoch}")
    print(f"Written: {written} | Skipped (already existed): {skipped}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
